let activeChapter=1;
const DATA_BASE='../library/textbooks/cc3e3/banks/';
const REVIEW_KEY='cc3_family_review_v2';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function asList(v){if(Array.isArray(v))return v;if(v===null||v===undefined||v==='')return [];if(typeof v==='string')return v.split(';').map(x=>x.trim()).filter(Boolean);return [String(v)]}
async function getJson(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(path+' ('+r.status+')');return r.json()}
function reviews(){try{return JSON.parse(localStorage.getItem(REVIEW_KEY)||'{}')}catch{return {}}}
function saveReviews(x){localStorage.setItem(REVIEW_KEY,JSON.stringify(x))}
function setReview(fid,status,note){const r=reviews();r[fid]={status,note:note??r[fid]?.note??'',updated_at:new Date().toISOString()};saveReviews(r);}
function reviewControls(f){const r=reviews()[f.family_id]||{};return `<div class="review" data-review="${esc(f.family_id)}"><div class="review-title">Teacher family review</div><div class="review-buttons"><button data-status="good" class="${r.status==='good'?'active good':''}">Good</button><button data-status="needs_work" class="${r.status==='needs_work'?'active needs_work':''}">Needs work</button><button data-status="bad" class="${r.status==='bad'?'active bad':''}">Bad family</button></div><textarea placeholder="Optional note">${esc(r.note||'')}</textarea></div>`}
function familyCard(f,ic,focus){const ex=f.exemplar||{},products=asList(f.product_eligibility).map(x=>`<span class="product">${esc(x.replaceAll('_',' '))}</span>`).join(''),tc=f.template_contract||{};return `<article class="family ${focus?'focus-col':''}" id="${esc(f.family_id)}"><div class="family-head"><span class="qid">${esc(f.teacher_question_id)}</span><span class="badge">${esc(f.family_id)}</span><span class="family-name">${esc(f.family_name)}</span></div><div class="ican-mini">${esc(ic.id)} · ${esc(ic.text)}</div><p class="purpose">${esc(f.family_purpose)}</p><div class="meta">${esc(f.question_structure_id)} · ${esc(f.response_mode)} · ${esc(f.representation_mode)}</div><div class="product-row">${products}</div><div class="question"><h4>Exemplar</h4>${ex.student_html||'<p>Exemplar unavailable.</p>'}</div><details><summary>Answer + short solution</summary><p><strong>Answer:</strong> ${esc(ex.answer)}</p><p>${esc(ex.solution)}</p></details><details><summary>Family specification</summary><dl><dt>Evidence job</dt><dd>${esc(f.evidence_job)}</dd><dt>Student action</dt><dd>${esc(f.student_action)}</dd><dt>Invariant</dt><dd>${esc(f.invariant)}</dd><dt>Allowed variation</dt><dd>${esc(asList(f.variation_axes).join('; '))}</dd><dt>Forbidden</dt><dd>${esc(asList(f.forbidden_variations).join('; '))}</dd><dt>Render route</dt><dd>${esc(tc.render_route||'')}</dd><dt>Status</dt><dd>${esc(f.approval_status)} · revision ${esc(f.family_revision)}</dd></dl></details><details><summary>Locked template contract</summary><dl><dt>Prompt</dt><dd>${esc(tc.prompt_template||'')}</dd><dt>Parameters</dt><dd>${esc(JSON.stringify(tc.parameters||{}))}</dd><dt>Constraints</dt><dd>${esc(asList(tc.constraints).join('; '))}</dd><dt>Answer rule</dt><dd>${esc(tc.answer_rule||'')}</dd><dt>Runtime rule</dt><dd>${tc.wording_locked?'Wording/structure locked; controlled parameter swaps only.':''}</dd></dl></details>${reviewControls(f)}</article>`}
function wireReviews(){document.querySelectorAll('[data-review]').forEach(box=>{const fid=box.dataset.review,ta=box.querySelector('textarea');box.querySelectorAll('button[data-status]').forEach(btn=>btn.onclick=()=>{setReview(fid,btn.dataset.status,ta.value);wireOneReview(box,fid)});ta.onchange=()=>{const r=reviews()[fid]||{};setReview(fid,r.status||'',ta.value)}})}
function wireOneReview(box,fid){const r=reviews()[fid]||{};box.querySelectorAll('button[data-status]').forEach(b=>{b.className='';if(b.dataset.status===r.status)b.className='active '+r.status})}
function exportReview(){const r=reviews();const payload={schema:'cc3-family-review/v2',exported_at:new Date().toISOString(),bank:'CC3',chapter:activeChapter,reviews:r};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`CC3_Chapter${activeChapter}_Family_Review.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function load(){const mode=document.body.dataset.mode;const manifest=await getJson(DATA_BASE+'BANK_MANIFEST.json');const params=new URLSearchParams(location.search);let chapter=Number(params.get('chapter')||1);activeChapter=chapter;const chapterSelect=document.getElementById('chapterSelect');manifest.chapters.forEach(c=>chapterSelect.add(new Option('Chapter '+c.chapter+(c.status==='DRAFT_REVIEW'?' · review':''),c.chapter)));chapterSelect.value=String(chapter);chapterSelect.onchange=()=>{const n=chapterSelect.value;location.href=mode+'.html?chapter='+n};document.getElementById('bankHome').onclick=()=>location.href='index.html';document.getElementById('exportReview').onclick=exportReview;const entry=manifest.chapters.find(c=>c.chapter===chapter);if(!entry||!entry.data){renderPending(chapter,mode);return}const data=await getJson(DATA_BASE+entry.data);if(mode==='section')renderSection(data,params);else renderMG(data,params);if(window.MathJax?.typesetPromise)await MathJax.typesetPromise();wireReviews()}
function renderPending(chapter,mode){document.getElementById('title').textContent='Chapter '+chapter+' Bank';document.getElementById('subtitle').textContent='Pending gold-standard conversion.';document.getElementById('count').textContent='Chapter 1 is the current review model.';document.getElementById('goalBanner').innerHTML='<div class="pending"><strong>Not built yet.</strong> This chapter will use the same family schema and review workflow after Chapter 1 is approved.</div>';document.getElementById('icanHeads').innerHTML='';document.getElementById('familyRows').innerHTML='';document.getElementById('scopeSelect').innerHTML='';document.getElementById('icanSelect').innerHTML=''}
function fillIcanSelect(icans,current){const ic=document.getElementById('icanSelect');ic.innerHTML='';ic.add(new Option('Show all I Cans',''));icans.forEach(x=>ic.add(new Option(`${x.id} · ${x.text}`,x.id)));ic.value=current||'';ic.onchange=()=>{const p=new URLSearchParams(location.search);if(ic.value)p.set('ican',ic.value);else p.delete('ican');location.search=p.toString()}}
function renderRows(data,icans,focus){const famById=new Map(data.families.map(f=>[f.family_id,f]));document.documentElement.style.setProperty('--ican-cols',Math.max(1,icans.length));document.getElementById('icanHeads').innerHTML=icans.map(ic=>`<div class="ican-head ${focus===ic.id?'focus-col':''}">${esc(ic.id)}<br>${esc(ic.text)}</div>`).join('');const max=Math.max(0,...icans.map(ic=>(ic.family_ids||[]).length));const rows=document.getElementById('familyRows');rows.innerHTML='';for(let i=0;i<max;i++){const l=document.createElement('div');l.className='row-label';l.textContent='Family '+(i+1);rows.appendChild(l);const row=document.createElement('div');row.className='family-row';row.innerHTML=icans.map(ic=>{const fid=(ic.family_ids||[])[i],f=famById.get(fid);return f?familyCard(f,ic,focus===ic.id):'<div class="family muted">No family in this row.</div>'}).join('');rows.appendChild(row)}}
function renderSection(data,params){document.getElementById('scopeLabel').textContent='Section';const sel=document.getElementById('scopeSelect');data.sections.forEach(s=>sel.add(new Option(`${s.section} · ${s.title}`,s.section)));let sec=params.get('section')||data.sections[0].section;sel.value=sec;sel.onchange=()=>location.href=`section.html?chapter=${data.chapter}&section=${encodeURIComponent(sel.value)}`;const s=data.sections.find(x=>x.section===sec)||data.sections[0];const focus=params.get('ican')||'';fillIcanSelect(s.i_cans,focus);document.getElementById('title').textContent=`Chapter ${data.chapter} · Section ${s.section} Bank`;document.getElementById('subtitle').textContent=s.title;const total=s.i_cans.reduce((n,ic)=>n+(ic.family_ids||[]).length,0);document.getElementById('count').textContent=`${s.i_cans.length} I Cans · ${total} family placements · teacher review`;document.getElementById('goalBanner').innerHTML=`<h2>${esc(s.section)} · ${esc(s.title)}</h2><p><strong>Learning Target:</strong> ${esc(s.learning_target)}</p><p class="muted">${s.progression.assessable_now?'This lesson includes assessment-ready evidence.':'Developing/practice emphasis at this point in the course.'}</p>`;renderRows(data,s.i_cans,focus)}
function renderMG(data,params){document.getElementById('scopeLabel').textContent='Mastery Goal';const sel=document.getElementById('scopeSelect');data.mastery_goals.forEach(m=>sel.add(new Option(`${m.id} · ${m.title}`,m.id)));let mid=params.get('mg')||data.mastery_goals[0].id;sel.value=mid;sel.onchange=()=>location.href=`mg.html?chapter=${data.chapter}&mg=${encodeURIComponent(sel.value)}`;const m=data.mastery_goals.find(x=>x.id===mid)||data.mastery_goals[0];const focus=params.get('ican')||'';fillIcanSelect(m.i_cans,focus);document.getElementById('title').textContent=`${m.id} · ${m.title}`;document.getElementById('subtitle').textContent=m.mastery_goal;const total=m.i_cans.reduce((n,ic)=>n+(ic.family_ids||[]).length,0);document.getElementById('count').textContent=`${m.i_cans.length} I Cans · ${total} family placements · teacher review`;document.getElementById('goalBanner').innerHTML=`<h2>${esc(m.id)} · ${esc(m.title)}</h2><p><strong>Mastery Goal:</strong> ${esc(m.mastery_goal)}</p><p class="muted">Only families mapped to mastery evidence appear here. The same canonical family may also appear in a lesson/section bank.</p>`;renderRows(data,m.i_cans,focus)}
window.addEventListener('DOMContentLoaded',()=>load().catch(err=>{document.getElementById('familyRows').innerHTML=`<div class="error">${esc(err.message)}</div>`}))