(function(){
  const NAMES=['Jordan','Maya','Sam','Alex','Riley','Taylor','Morgan','Casey','Avery','Cameron'];
  const pick=a=>a[Math.floor(Math.random()*a.length)];
  const ri=(a,b,nonzero=false)=>{let n;do{n=Math.floor(Math.random()*(b-a+1))+a}while(nonzero&&n===0);return n};
  const shuffle=a=>{a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
  const letter=i=>'ABCD'[i]||String(i+1);
  const math=s=>`\\(${s}\\)`;
  const pair=(x,y)=>`(${x},${y})`;
  const dirX=x=>x<0?'left':'right';
  const dirY=y=>y<0?'down':'up';
  const uniqueInts=(count,min,max,nonzero=false)=>{const s=new Set();while(s.size<count)s.add(ri(min,max,nonzero));return [...s]};
  const choiceHtml=(choices)=>`<ol class="choices">${choices.map(c=>`<li>${c}</li>`).join('')}</ol>`;
  function mc(prompt,choices,correct,solution){
    const mixed=shuffle(choices.map((text,i)=>({text,correct:i===correct})));const idx=mixed.findIndex(x=>x.correct);
    return {student_html:`<p>${prompt}</p>${choiceHtml(mixed.map(x=>x.text))}`,answer:`${letter(idx)}. ${mixed[idx].text.replace(/<[^>]*>/g,'')}`,solution:solution||''};
  }
  function coordPlaneSvg(point=null,label='P'){
    const W=420,H=420,pad=30,step=(W-2*pad)/20,toX=x=>pad+(x+10)*step,toY=y=>H-pad-(y+10)*step;let grid='';
    for(let v=-10;v<=10;v++){const x=toX(v),y=toY(v);grid+=`<line x1="${x}" y1="${pad}" x2="${x}" y2="${H-pad}" stroke="#d9dee5" stroke-width="1"/><line x1="${pad}" y1="${y}" x2="${W-pad}" y2="${y}" stroke="#d9dee5" stroke-width="1"/>`;if(v%2===0&&v!==0)grid+=`<text x="${x}" y="${toY(0)+15}" text-anchor="middle" font-size="9">${v}</text><text x="${toX(0)-7}" y="${y+3}" text-anchor="end" font-size="9">${v}</text>`}
    const p=point?`<circle cx="${toX(point.x)}" cy="${toY(point.y)}" r="5" fill="#111"/><text x="${toX(point.x)+8}" y="${toY(point.y)-8}" font-size="15" font-weight="700">${label}</text>`:'';
    return `<svg class="graph generated-graph" viewBox="0 0 ${W} ${H}" role="img" aria-label="Coordinate plane"><rect width="100%" height="100%" fill="white"/>${grid}<line x1="${pad}" y1="${toY(0)}" x2="${W-pad}" y2="${toY(0)}" stroke="#111" stroke-width="2"/><line x1="${toX(0)}" y1="${pad}" x2="${toX(0)}" y2="${H-pad}" stroke="#111" stroke-width="2"/>${p}</svg>`;
  }
  function lineGraphSvg({m=10,b=0,xMax=8,yStep=10,yMax=null,xLabel='Input',yLabel='Output'}){
    yMax=yMax||Math.ceil((m*xMax+b)/yStep)*yStep;const W=500,H=330,L=54,R=18,T=18,B=44,toX=x=>L+x/xMax*(W-L-R),toY=y=>H-B-y/yMax*(H-T-B);let s=`<svg class="graph generated-graph" viewBox="0 0 ${W} ${H}" role="img" aria-label="${xLabel} versus ${yLabel} graph"><rect width="100%" height="100%" fill="white"/>`;
    for(let x=0;x<=xMax;x++){const px=toX(x);s+=`<line x1="${px}" y1="${T}" x2="${px}" y2="${H-B}" stroke="#e1e5ea"/><text x="${px}" y="${H-B+17}" text-anchor="middle" font-size="10">${x}</text>`}
    for(let y=0;y<=yMax;y+=yStep){const py=toY(y);s+=`<line x1="${L}" y1="${py}" x2="${W-R}" y2="${py}" stroke="#e1e5ea"/><text x="${L-7}" y="${py+3}" text-anchor="end" font-size="10">${y}</text>`}
    s+=`<line x1="${L}" y1="${H-B}" x2="${W-R}" y2="${H-B}" stroke="#111" stroke-width="2"/><line x1="${L}" y1="${T}" x2="${L}" y2="${H-B}" stroke="#111" stroke-width="2"/>`;
    const x2=Math.min(xMax,(yMax-b)/m);s+=`<line x1="${toX(0)}" y1="${toY(b)}" x2="${toX(x2)}" y2="${toY(m*x2+b)}" stroke="#1e4e79" stroke-width="3"/>`;
    s+=`<text x="${(L+W-R)/2}" y="${H-8}" text-anchor="middle" font-size="12">${xLabel}</text><text x="15" y="${(T+H-B)/2}" text-anchor="middle" font-size="12" transform="rotate(-90 15 ${(T+H-B)/2})">${yLabel}</text></svg>`;return s;
  }
  function interceptGraphSvg(a,b){
    const W=420,H=420,pad=30,step=(W-2*pad)/20,toX=x=>pad+(x+10)*step,toY=y=>H-pad-(y+10)*step;let grid='';for(let v=-10;v<=10;v++){const x=toX(v),y=toY(v);grid+=`<line x1="${x}" y1="${pad}" x2="${x}" y2="${H-pad}" stroke="#e1e5ea"/><line x1="${pad}" y1="${y}" x2="${W-pad}" y2="${y}" stroke="#e1e5ea"/>`;if(v%2===0&&v!==0)grid+=`<text x="${x}" y="${toY(0)+15}" text-anchor="middle" font-size="9">${v}</text><text x="${toX(0)-7}" y="${y+3}" text-anchor="end" font-size="9">${v}</text>`}
    const m=-b/a;const yAtNeg10=m*(-10)+b,yAt10=m*10+b;return `<svg class="graph generated-graph" viewBox="0 0 ${W} ${H}" role="img" aria-label="Line with intercepts"><rect width="100%" height="100%" fill="white"/>${grid}<line x1="${pad}" y1="${toY(0)}" x2="${W-pad}" y2="${toY(0)}" stroke="#111" stroke-width="2"/><line x1="${toX(0)}" y1="${pad}" x2="${toX(0)}" y2="${H-pad}" stroke="#111" stroke-width="2"/><line x1="${toX(-10)}" y1="${toY(yAtNeg10)}" x2="${toX(10)}" y2="${toY(yAt10)}" stroke="#1e4e79" stroke-width="3"/></svg>`;
  }
  function inst(html,answer,solution,note='Generated from the current approved family template.') {return {student_html:html,answer,solution,generation_note:note};}
  function scaleScenario(opts={}){const yStep=pick([10,20]),m=yStep,b=opts.zero?0:pick([0,yStep,2*yStep]),xMax=8;return {yStep,m,b,xMax,y:x=>m*x+b,svg:lineGraphSvg({m,b,xMax,yStep,xLabel:opts.xLabel||'Input',yLabel:opts.yLabel||'Output'})}}
  function gcd(a,b){a=Math.abs(a);b=Math.abs(b);while(b){const t=a%b;a=b;b=t}return a||1}
  function rat(n,d=1){if(d<0){n=-n;d=-d}const g=gcd(n,d);n/=g;d/=g;return {n,d,value:n/d,text:d===1?String(n):`${n<0?'-':''}\\frac{${Math.abs(n)}}{${d}}`}}
  function slopeGraphSvg(m,b=0,marked=false){
    const W=420,H=420,pad=34,step=(W-2*pad)/20,toX=x=>pad+(x+10)*step,toY=y=>H-pad-(y+10)*step;let grid='';
    for(let v=-10;v<=10;v++){const x=toX(v),y=toY(v);grid+=`<line x1="${x}" y1="${pad}" x2="${x}" y2="${H-pad}" stroke="#e1e5ea"/><line x1="${pad}" y1="${y}" x2="${W-pad}" y2="${y}" stroke="#e1e5ea"/>`;if(v%2===0&&v!==0)grid+=`<text x="${x}" y="${toY(0)+15}" text-anchor="middle" font-size="9">${v}</text><text x="${toX(0)-7}" y="${y+3}" text-anchor="end" font-size="9">${v}</text>`}
    let xA=-10,xB=10,yA=m*xA+b,yB=m*xB+b;const pts=[];for(let x=-8;x<=8;x++){const y=m*x+b;if(Number.isInteger(y)&&y>=-9&&y<=9)pts.push({x,y})}
    const marks=marked&&pts.length>=2?shuffle(pts).slice(0,2).map(p=>`<circle cx="${toX(p.x)}" cy="${toY(p.y)}" r="5" fill="#111"/>`).join(''):'';
    return `<svg class="graph generated-graph" viewBox="0 0 ${W} ${H}" role="img" aria-label="Coordinate graph of a line"><rect width="100%" height="100%" fill="white"/>${grid}<line x1="${pad}" y1="${toY(0)}" x2="${W-pad}" y2="${toY(0)}" stroke="#111" stroke-width="2"/><line x1="${toX(0)}" y1="${pad}" x2="${toX(0)}" y2="${H-pad}" stroke="#111" stroke-width="2"/><line x1="${toX(xA)}" y1="${toY(yA)}" x2="${toX(xB)}" y2="${toY(yB)}" stroke="#1e4e79" stroke-width="3"/>${marks}</svg>`;
  }
  function tableHtml(rows,xLabel='x',yLabel='y'){return `<table class="data-table"><tr><th>${xLabel}</th><th>${yLabel}</th></tr>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td></tr>`).join('')}</table>`}
  function linearRows(m,b,xs){return xs.map(x=>[x,m*x+b])}
  function signedTerm(m){if(m===1)return 'x';if(m===-1)return '-x';return `${m}x`}
  function linearEq(m,b){if(b===0)return `y=${signedTerm(m)}`;return `y=${signedTerm(m)}${b>0?'+':''}${b}`}
  function fracMath(r){return math(r.text)}
  function generate(fid){
    let x,y,h,v,d,a,b,n1,n2,q,choices,correct,student1,student2,sc;
    switch(fid){
      case 'U1-MG01-IC01-A': x=ri(-8,8,true);y=ri(-8,8,true);return inst(`<p>Plot the point ${math(`P(${x},${y})`)} on the coordinate plane.</p><img class="graph" src="https://tnezki.github.io/algebra/banks/unit1/figures/u1_mg01_blank_plane.png" alt="Blank coordinate plane from -10 to 10 on both axes"><div class="response-surface">Place and label point P.</div>`,`P is at (${x}, ${y}).`,'Use x first and y second.');
      case 'U1-MG01-IC01-B': h=ri(2,8);v=ri(2,8);x=pick([-h,h]);y=pick([-v,v]);return inst(`<p>Start at the origin. Move ${h} units ${dirX(x)} and ${v} units ${dirY(y)}. Write the ordered pair for the ending point.</p><div class="response-surface">Ordered pair: __________</div>`,pair(x,y),`${dirX(x)} determines the sign of x and ${dirY(y)} determines the sign of y.`);
      case 'U1-MG01-IC01-C': h=ri(2,8);v=ri(2,8);x=pick([-h,h]);y=pick([-v,v]);if(Math.random()<.5){const wrong=pair(-x,y);return mc(`A student moves ${h} units ${dirX(x)} and ${v} units ${dirY(y)}, but writes ${math(wrong)}. What is the error?`,[`The x-coordinate should be ${x}.`,`The y-coordinate should be ${-y}.`,'The coordinates should be switched.','There is no error.'],0,`The horizontal direction requires x=${x}.`)}else{const wrong=pair(x,-y);return mc(`A student moves ${h} units ${dirX(x)} and ${v} units ${dirY(y)}, but writes ${math(wrong)}. What is the error?`,[`The y-coordinate should be ${y}.`,`The x-coordinate should be ${-x}.`,'The coordinates should be switched.','There is no error.'],0,`The vertical direction requires y=${y}.`)}
      case 'U1-MG01-IC01-D': h=ri(2,8);v=ri(2,8);x=pick([-h,h]);y=pick([-v,v]);choices=[math(pair(x,y)),math(pair(-x,y)),math(pair(x,-y)),math(pair(y,x))];return mc(`Which ordered pair is ${h} units ${dirX(x)} and ${v} units ${dirY(y)} from the origin?`,choices,0,`${dirX(x)} gives x=${x}; ${dirY(y)} gives y=${y}.`);
      case 'U1-MG01-IC01-E': x=ri(-8,8,true);y=ri(-8,8,true);do{n1=ri(-8,8);n2=ri(-8,8)}while(n1===x&&n2===y);return inst(`<p>Plot and label A${math(pair(x,y))} and B${math(pair(n1,n2))}.</p><img class="graph" src="https://tnezki.github.io/algebra/banks/unit1/figures/u1_mg01_blank_plane.png" alt="Blank coordinate plane from -10 to 10"><div class="response-surface">Plot both points.</div>`,`A=${pair(x,y)}; B=${pair(n1,n2)}`,'Use x first and y second for each point.');
      case 'U1-MG01-IC01-F': h=ri(2,8);v=ri(2,8);x=pick([-h,h]);y=pick([-v,v]);[student1,student2]=shuffle(NAMES).slice(0,2);if(Math.random()<.5){return inst(`<p>${student1}: “${h} ${dirX(x)}, ${v} ${dirY(y)} → ${math(pair(x,y))}.” ${student2}: “${h} ${dirX(x)}, ${v} ${dirY(y)} → ${math(pair(-x,-y))}.” Who is correct? Why?</p><div class="response-surface">Answer:</div>`,student1,`${dirX(x)} gives x=${x} and ${dirY(y)} gives y=${y}.`)}return inst(`<p>${student1}: “${h} ${dirX(x)}, ${v} ${dirY(y)} → ${math(pair(-x,-y))}.” ${student2}: “${h} ${dirX(x)}, ${v} ${dirY(y)} → ${math(pair(x,y))}.” Who is correct? Why?</p><div class="response-surface">Answer:</div>`,student2,`${dirX(x)} gives x=${x} and ${dirY(y)} gives y=${y}.`);
      case 'U1-MG01-IC01-G': q=pick(['I','II','III','IV']);const signs={I:[1,1],II:[-1,1],III:[-1,-1],IV:[1,-1]}[q];choices=[];for(let i=0;i<3;i++)choices.push(math(pair(signs[0]*ri(1,8),signs[1]*ri(1,8))));const oq=pick(Object.keys({I:1,II:1,III:1,IV:1}).filter(z=>z!==q));const os={I:[1,1],II:[-1,1],III:[-1,-1],IV:[1,-1]}[oq];choices.push(math(pair(os[0]*ri(1,8),os[1]*ri(1,8))));return mc(`Which point is not in Quadrant ${q}?`,choices,3,`Quadrant ${q} has sign pattern (${signs[0]>0?'+':'-'}, ${signs[1]>0?'+':'-'}).`);
      case 'U1-MG01-IC01-H': x=ri(-8,8,true);y=ri(-8,8,true);q=pick(['P','Q','R','S','T']);return inst(`<p>Use the graph. What are the coordinates of point ${q}? Write your answer as an ordered pair.</p>${coordPlaneSvg({x,y},q)}<div class="response-surface">Ordered pair: __________</div>`,pair(x,y),`Read x first and y second: ${pair(x,y)}.`);
      case 'U1-MG01-IC01-I': x=ri(-8,8,true);y=ri(-8,8,true);const wrongX=Math.random()<.5;const hd=wrongX?dirX(-x):dirX(x),vd=wrongX?dirY(y):dirY(-y);return inst(`<p>Claim: ${math(pair(x,y))} means ${Math.abs(x)} units ${hd} and ${Math.abs(y)} units ${vd}. Correct or incorrect? Fix it if needed.</p><div class="response-surface">Answer:</div>`,`Incorrect; it is ${Math.abs(x)} units ${dirX(x)} and ${Math.abs(y)} units ${dirY(y)}.`,`Check each coordinate sign against its movement direction.`);
      case 'U1-MG01-IC01-J': y=ri(-9,9);d=ri(1,9);q=pick(['left','right']);x=q==='left'?-d:d;return inst(`<p>${math(`T(\\square, ${y})`)} is ${d} units ${q} of the y-axis. Fill in the missing x-coordinate.</p><div class="response-surface">x = _____</div>`,String(x),`${d} units ${q} of the y-axis means x=${x}.`);
      case 'U1-MG01-IC02-A': x=ri(-8,8,true);y=ri(-8,8,true);return inst(`<p>For ${math(`Q${pair(x,y)}`)}, move _____ units ${dirX(x)}, then _____ units ${dirY(y)}.</p>`,`${Math.abs(x)}; ${Math.abs(y)}`,'The first coordinate gives the horizontal move; the second gives the vertical move.');
      case 'U1-MG01-IC02-B': choices=[math(pair(ri(-8,8,true),0)),math(pair(0,ri(-8,8,true))),math(pair(ri(-8,8,true),ri(-8,8,true))),math(pair(ri(-8,8,true),ri(-8,8,true)))];return mc('Which point lies on the x-axis?',choices,0,'A point lies on the x-axis when y=0.');
      case 'U1-MG01-IC02-C': x=ri(-8,8,true);y=ri(-8,8,true);return mc(`To plot ${math(`R${pair(x,y)}`)}, a student moves ${Math.abs(y)} units ${dirX(x)} and ${Math.abs(x)} units ${dirY(y)}. What did the student do wrong?`,['The student switched the coordinates.','The student used the wrong signs.','The student started on the wrong axis.','The student made no error.'],0,'The x-value controls horizontal movement and the y-value controls vertical movement.');
      case 'U1-MG01-IC02-D': x=ri(-9,9,true);y=ri(-9,9,true);choices=[`x: ${Math.abs(x)} ${dirX(x)}; y: ${Math.abs(y)} ${dirY(y)}`,`x: ${Math.abs(y)} ${dirY(y)}; y: ${Math.abs(x)} ${dirX(x)}`,`x: ${Math.abs(x)} ${dirX(-x)}; y: ${Math.abs(y)} ${dirY(-y)}`,`x: ${Math.abs(y)} ${dirX(x)}; y: ${Math.abs(x)} ${dirY(y)}`];return mc(`Which statement is correct for ${math(pair(x,y))}?`,choices,0,'The first coordinate is x/horizontal; the second is y/vertical.');
      case 'U1-MG01-IC02-E': {const contexts=[['time (min)','distance (m)','After {x} min, the distance is {y} m.'],['hours','cost ($)','After {x} hours, the cost is ${y}.'],['days','height (cm)','After {x} days, the height is {y} cm.']];const c=pick(contexts);x=ri(2,8);y=ri(10,80);choices=[c[2].replace('{x}',x).replace('{y}',y),c[2].replace('{x}',y).replace('{y}',x),`The rate is ${y} per ${x}.`,`The starting value is ${x}.`];return mc(`A graph uses x = ${c[0]} and y = ${c[1]}. What does the point ${math(pair(x,y))} mean?`,choices,0,'Interpret the first coordinate with the x-axis quantity and the second with the y-axis quantity.');}
      case 'U1-MG01-IC02-F': {const c=pick([['Temperature','hour','hour','temperature'],['Distance','minute','time','distance'],['Cost','day','day','cost']]);return inst(`<p>${c[0]} is recorded each ${c[1]}. Which setup better shows change over time?</p><p><b>A.</b> x = ${c[2]}, y = ${c[3]}<br><b>B.</b> x = ${c[3]}, y = ${c[2]}</p><div class="response-surface">Choice: _____</div>`,'A','The input/time quantity belongs on x.');}
      case 'U1-MG01-IC02-G': return inst('<p>For any point on the y-axis, \(x=\) _____.</p>','0','Every point on the y-axis has x=0.','Static approved family; wording has no declared variable parameter.');
      case 'U1-MG01-IC02-H': choices=shuffle(['input','output','x-axis','y-axis']);return inst(`<p><b>Word bank:</b> ${choices.join(', ')}</p><p>Put the <b>_____</b> quantity on the x-axis and the <b>_____</b> quantity on the y-axis.</p>`,'input; output','Input belongs on x; output belongs on y.');
      case 'U1-MG01-IC02-I': x=ri(-8,8,true);y=ri(-8,8);return inst(`<p>A point has coordinates ${math(pair(x,y))}. Which number tells how far left or right the point is located? Explain what that number tells you.</p><div class="response-surface">Answer:</div>`,`${x}; it is the x-coordinate and means the point is ${Math.abs(x)} units to the ${dirX(x)} of the y-axis.`,'The x-coordinate controls horizontal position.');
      case 'U1-MG01-IC02-J': x=ri(-7,7);do{n1=ri(-7,7)}while(n1===x);y=ri(-7,7);do{n2=ri(-7,7)}while(n2===y);return inst(`<p>From ${math(pair(x,y))} to ${math(pair(n1,y))}, only the _____-coordinate changes.<br>From ${math(pair(n1,y))} to ${math(pair(n1,n2))}, only the _____-coordinate changes.</p>`,'x; y','Horizontal change alters x; vertical change alters y.');
      case 'U1-MG01-IC03-A': sc=scaleScenario({xLabel:'Time (min)',yLabel:'Distance (m)'});x=ri(2,6);return inst(`<p>Use the graph. At ${math(`t=${x}`)} minutes, what distance is shown?</p>${sc.svg}<div class="response-surface">Distance: __________ m</div>`,`${sc.y(x)} m`,'Read the y-value at the stated time.');
      case 'U1-MG01-IC03-B': sc=scaleScenario({xLabel:'Time (min)',yLabel:'Water (L)'});n1=ri(1,3);n2=ri(5,8);return inst(`<p>Use the graph. How much more water is shown at ${n2} minutes than at ${n1} minutes?</p>${sc.svg}<div class="response-surface">Show the two readings and the difference.</div>`,`${sc.y(n2)-sc.y(n1)} L`,`Read ${sc.y(n1)} L and ${sc.y(n2)} L; subtract.`);
      case 'U1-MG01-IC03-C': sc=scaleScenario();q=pick(['x','y']);return inst(`<p>Use the graph. What is the scale of the ${q}-axis?</p>${sc.svg}<div class="response-surface">Scale: _____</div>`,q==='x'?'1':String(sc.yStep),`Consecutive ${q}-axis gridlines differ by ${q==='x'?1:sc.yStep}.`);
      case 'U1-MG01-IC03-D': sc=scaleScenario({xLabel:'Time (min)',yLabel:'Distance (m)'});x=ri(2,6);y=sc.y(x);choices=[`${x} m`,`${Math.round(y/sc.yStep)} m`,`${x*10} m`,`${y} m`];return mc(`Use the graph. At ${math(`t=${x}`)} minutes, which distance is shown?${sc.svg}`,choices,3,'Read the labeled y-axis scale at the stated x-value.');
      case 'U1-MG01-IC03-E': sc=scaleScenario();x=ri(2,6)+.5;y=sc.y(x);return inst(`<p>Estimate the output when the input is ${x}.</p>${sc.svg}<div class="response-surface">Estimated output: _____</div>`,`Accept ${Math.round(y)-1}-${Math.round(y)+1}.`,'Estimate between the neighboring grid values.');
      case 'U1-MG01-IC03-F': sc=scaleScenario();x=ri(2,6);return inst(`<p>Use the graph. When the input is ${x}, what is the output?</p>${sc.svg}<div class="response-surface">Output: _____</div>`,String(sc.y(x)),'Read the y-value at the stated input.');
      case 'U1-MG01-IC03-G': sc=scaleScenario({zero:true,xLabel:'Time (min)',yLabel:'Distance (m)'});x=ri(2,6);y=sc.y(x);[student1,student2]=shuffle(NAMES).slice(0,2);return inst(`<p>At ${x} minutes, ${student1} says ${y/sc.yStep} m. ${student2} says ${y} m. Who read the scale correctly?</p>${sc.svg}<div class="response-surface">Student: _____</div>`,student2,`${student2} used the labeled y-axis scale.`);
      case 'U1-MG01-IC03-H': sc=scaleScenario();x=ri(2,6);y=sc.y(x);return inst(`<p>Use the graph. The output is ${y}. What input produces this output?</p>${sc.svg}<div class="response-surface">Input: _____</div>`,String(x),'Read across from the output to the line and down to the input.');
      case 'U1-MG01-IC03-I': sc=scaleScenario();x=ri(2,6)+.5;y=sc.y(x);choices=[Math.round(y-sc.yStep*1.5),Math.round(y-sc.yStep*.5),Math.round(y),Math.round(y+sc.yStep*1.5)].map(String);return mc(`At input ${x}, which is the best estimate of the output?${sc.svg}`,choices,2,'Choose the value closest to the line at the stated input.');
      case 'U1-MG01-IC03-J': sc=scaleScenario({zero:true,xLabel:'Time (min)',yLabel:'Distance (m)'});x=ri(2,6);y=sc.y(x);student1=pick(NAMES);return inst(`<p>${student1} says the output when the input is ${x} is ${y/sc.yStep}.</p>${sc.svg}<p>Explain ${student1}'s mistake and give the correct output.</p><div class="response-surface">Explain:</div>`,`${student1} counted gridlines instead of reading the y-axis scale. The correct output is ${y}.`,'Each y-gridline represents the labeled scale, not 1 unit.');
      case 'U1-MG01-IC04-A': a=ri(-7,7,true);b=ri(-7,7,true);return inst(`<p>Identify the x-intercept and y-intercept of the line.</p>${interceptGraphSvg(a,b)}<div class="response-surface">x-intercept: ______ &nbsp; y-intercept: ______</div>`,`x-intercept (${a},0); y-intercept (0,${b}).`,'An x-intercept has y=0; a y-intercept has x=0.');
      case 'U1-MG01-IC04-B': b=pick([10,20,30,40]);const rate=pick([5,10]);sc={svg:lineGraphSvg({m:rate,b,xMax:8,yStep:10,xLabel:'Hours',yLabel:'Cost ($)'})};return inst(`<p>The graph shows a service cost over time.</p>${sc.svg}<p>What does the y-intercept mean in this situation?</p><div class="response-surface">Interpretation:</div>`,`The cost is $${b} at 0 hours; $${b} is the starting fee.`,'The y-intercept is the starting value when x=0.');
      case 'U1-MG01-IC04-C': a=ri(-9,9,true);student1=pick(NAMES);return inst(`<p>${student1} says ${math(pair(a,0))} is the y-intercept. Describe the mistake and write it correctly.</p><div class="response-surface">Explain and correct:</div>`,`${pair(a,0)} is the x-intercept, not the y-intercept, because its y-coordinate is 0.`,'x-intercepts lie on the x-axis, so y=0.');
      case 'U1-MG01-IC04-D': a=ri(-7,7,true);b=ri(-7,7,true);choices=[`x=${math(pair(a,0))}, y=${math(pair(0,b))}`,`x=${math(pair(0,b))}, y=${math(pair(a,0))}`,`x=${a}, y=${b} with coordinates reversed`,`x=${math(pair(b,0))}, y=${math(pair(0,a))}`];return mc(`Use the graph. Which choice correctly gives the x-intercept and y-intercept?${interceptGraphSvg(a,b)}`,choices,0,'x-intercept has y=0; y-intercept has x=0.');
      case 'U1-MG01-IC04-E': if(Math.random()<.5){a=ri(-8,8,true);return inst(`<p>The graph shows the intercept ${math(pair(a,0))}. Is it an x-intercept or y-intercept? How do you know?</p><div class="response-surface">Type + reason:</div>`,'x-intercept','Its y-coordinate is 0.')}b=ri(-8,8,true);return inst(`<p>The graph shows the intercept ${math(pair(0,b))}. Is it an x-intercept or y-intercept? How do you know?</p><div class="response-surface">Type + reason:</div>`,'y-intercept','Its x-coordinate is 0.');
      case 'U1-MG01-IC04-F': return inst('<p>What does the y-intercept of a graph mean?</p><div class="response-surface">Explain:</div>','It is the point where the graph crosses the y-axis.','Its x-coordinate is 0.','Static approved family; wording has no declared variable parameter.');
      case 'U1-MG01-IC04-G': return mc('What does the y-intercept of a graph represent?',['Where the graph crosses the x-axis','Where the graph crosses the y-axis','The greatest point on the graph','The point where x=y'],1,'The y-intercept is where the graph crosses the y-axis.');
      case 'U1-MG01-IC04-H': return inst('<p>What does the x-intercept of a graph mean?</p><div class="response-surface">Explain:</div>','It is the point where the graph crosses the x-axis.','Its y-coordinate is 0.','Static approved family; wording has no declared variable parameter.');
      case 'U1-MG01-IC04-I': a=ri(-7,7,true);b=ri(-7,7,true);return inst(`<p>Graph a line with x-intercept ${math(pair(a,0))} and y-intercept ${math(pair(0,b))}.</p><img class="graph" src="https://tnezki.github.io/algebra/banks/unit1/figures/u1_mg01_blank_plane.png" alt="Blank coordinate plane from -10 to 10"><div class="response-surface">Plot both intercepts and draw the line.</div>`,`Line through (${a},0) and (0,${b}).`,'Plot both intercepts and draw the line through them.');
      case 'U1-MG01-IC04-J': return inst('<p>The x-intercept is the point where a graph crosses the <b>_____</b>.</p>','x-axis','The x-intercept lies on the x-axis.','Static approved family; wording has no declared variable parameter.');
      case 'U1-MG02-IC01-A': {const m=pick([-3,-2,-1,1,2,3]),b=ri(-4,4);return inst(`<p>Find the slope of the line. Show a rise/run calculation using two points from the graph.</p>${slopeGraphSvg(m,b,true)}<div class="response-surface">Rise/run:</div>`,String(m),`A rise/run pair simplifies to ${m}.`);}
      case 'U1-MG02-IC01-B': {const r=pick([rat(-1,2),rat(-2,3),rat(-3,2)]),b=ri(-2,4);return inst(`<p>Find the slope of the line, then explain what the negative sign tells you about the graph.</p>${slopeGraphSvg(r.value,b,true)}<div class="response-surface">Slope + explanation:</div>`,`${r.text}; y decreases as x increases.`,`The line descends from left to right, so the slope is negative.`);}
      case 'U1-MG02-IC01-C': {const r=pick([rat(1,2),rat(2,3),rat(3,2),rat(2,1)]),claim=rat(-r.n,r.d);return inst(`<p>A student says the slope of this line is ${fracMath(claim)}. How do you know this is wrong?</p>${slopeGraphSvg(r.value,ri(-3,3),false)}<div class="response-surface">Explain:</div>`,'The line rises from left to right, so its slope must be positive.','A rising line has positive slope.');}
      case 'U1-MG02-IC01-D': {const run=pick([1,2,3]),rise=pick([-6,-4,-3,-2,2,3,4,6]),m=rise/run,b=ri(-3,3),x1=0,y1=b,x2=run,y2=b+rise;return mc(`Using points ${math(pair(x1,y1))} and ${math(pair(x2,y2))}, which rise/run matches the line?${slopeGraphSvg(m,b,true)}`,[`rise ${rise}, run ${run}`,`rise ${run}, run ${rise}`,`rise ${-rise}, run ${run}`,`rise ${rise}, run ${-run}`],0,`Rise = ${rise}; run = ${run}.`);}
      case 'U1-MG02-IC01-E': {const r=pick([rat(1,2),rat(-1,2),rat(2,1),rat(-2,1),rat(3,2),rat(-3,2)]),op=rat(-r.n,r.d),big=rat((r.n<0?-1:1)*(Math.abs(r.n)+2*r.d),r.d),negBig=rat(-big.n,big.d);return mc(`Which is the best estimate of the slope of the line?${slopeGraphSvg(r.value,ri(-2,2),false)}`,[fracMath(r),fracMath(op),fracMath(big),fracMath(negBig)],0,'Match both the direction and approximate steepness.');}
      case 'U1-MG02-IC01-F': {const base=pick([rat(1,2),rat(2,3),rat(-1,2),rat(-2,3),rat(2,1)]),k1=pick([2,3]),k2=pick([4,5]);return inst(`<p>One student uses rise/run ${math(`${base.n*k1}/${base.d*k1}`)}; another uses ${math(`${base.n*k2}/${base.d*k2}`)}. Can both describe the same line? Why?</p><div class="response-surface">Answer:</div>`,'Yes; the two ratios are equivalent.',`Both simplify to ${base.text}.`);}
      case 'U1-MG02-IC01-G': {const m=pick([-3,-2,-1,1,2,3]),b=ri(-3,3);return inst(`<p>Use the two marked points on the graph. Find the slope of the line.</p>${slopeGraphSvg(m,b,true)}<div class="response-surface">Slope: _____</div>`,String(m),'Compute change in y divided by change in x.');}
      case 'U1-MG02-IC01-H': {const rise=pick([-6,-4,-3,-2,2,3,4,6]),run=pick([1,2,3,4]);const r=rat(rise,run),rec=rat(run,rise);return inst(`<p>A student measures rise ${rise} and run ${run} but reports slope ${fracMath(rec)}. Critique the claim.</p><div class="response-surface">Critique:</div>`,`The ratio is reversed; slope is rise/run = ${r.text}.`,'Slope is rise divided by run.');}
      case 'U1-MG02-IC01-I': {const m=pick([-3,-2,-1,1,2,3]),b=ri(-3,3);return inst(`<p>On the graphed line, choose two lattice points you would use to find slope and explain why they are useful.</p>${slopeGraphSvg(m,b,true)}<div class="response-surface">Points + reason:</div>`,'Any two visible lattice points on the line that give the correct slope.',`A convenient pair should produce slope ${m}.`);}
      case 'U1-MG02-IC01-J': {const r=pick([rat(1,2),rat(-1,2),rat(2,1),rat(-2,1)]),claim=Math.random()<.5?r:rat(-r.n,r.d);const ok=claim.n===r.n&&claim.d===r.d;return inst(`<p>Claim: “The slope of this line is ${fracMath(claim)}.” Verify the claim.</p>${slopeGraphSvg(r.value,ri(-2,2),true)}<div class="response-surface">Verification:</div>`,ok?'True.':`False; the slope is ${r.text}.`,'Check the sign, then compute rise/run.');}
      case 'U1-MG02-IC02-A': {const m=pick([-4,-3,-2,2,3,4]),b=ri(-5,5),x0=ri(-3,0),xs=[x0,x0+2,x0+4];return inst(`<p>Find the slope represented by the table.</p>${tableHtml(linearRows(m,b,xs))}<div class="response-surface">Slope: ______</div>`,String(m),'Use change in y divided by change in x.');}
      case 'U1-MG02-IC02-B': {const m=pick([-4,-3,-2,2,3,4]),b=ri(-5,5),x0=ri(-2,2),xs=[x0,x0+3,x0+7];return inst(`<p>Find the slope represented by the table.</p>${tableHtml(linearRows(m,b,xs))}<div class="response-surface">Show Δy and Δx.</div>`,String(m),'The unequal x-steps still give the same rate.');}
      case 'U1-MG02-IC02-C': {const m=pick([2,3,4]),b=ri(-4,4),x1=ri(0,3),x2=x1+3,y1=m*x1+b,y2=m*x2+b,dy=y2-y1;return inst(`<p>A student uses the table and says, “The slope is ${dy} because y changes by ${dy}.”</p>${tableHtml([[x1,y1],[x2,y2]])}<p>Explain the error and give the correct slope.</p><div class="response-surface">Diagnosis:</div>`,`Slope is ${m}, not ${dy}, because Δx=${x2-x1} and Δy=${dy}.`,'Slope requires Δy/Δx.');}
      case 'U1-MG02-IC02-D': {const m=pick([-5,-4,-3,2,3,4,5]),x1=ri(1,6),x2=x1+1,y1=ri(1,12),y2=y1+m;return inst(`<p>Use the two rows in the table. Find the slope.</p>${tableHtml([[x1,y1],[x2,y2]])}<div class="response-surface">Slope: _____</div>`,String(m),`(${y2}-${y1})/(${x2}-${x1})=${m}.`);}
      case 'U1-MG02-IC02-E': {const m=pick([2,3,4,-2,-3]),b=ri(-4,5),x1=ri(0,3),x2=x1+3,x3=x2+2,y1=m*x1+b,y2=m*x2+b,y3=m*x3+b;return inst(`<p>The table has slope ${m}. Find the missing y-value.</p>${tableHtml([[x1,y1],[x2,y2],[x3,'?']])}<div class="response-surface">Missing y: ___</div>`,String(y3),`Continue the linear rule with slope ${m}.`);}
      case 'U1-MG02-IC02-F': {const m=pick([-4,-3,-2,2,3,4]),b=ri(-4,4),x1=ri(-2,2),x2=x1+2,y1=m*x1+b,y2=m*x2+b;return mc(`What slope is represented?${tableHtml([[x1,y1],[x2,y2]])}`,[String(m),String(y2-y1),String(1/m),String(-m)],0,'Compute Δy/Δx.');}
      case 'U1-MG02-IC02-G': {const m=pick([-4,-3,-2,2,3,4]),x1=ri(-4,2),y1=ri(-5,5),dx=pick([1,2,3]),x2=x1+dx,y2=y1+m*dx;return inst(`<p>Find the slope through the points ${math(pair(x1,y1))} and ${math(pair(x2,y2))}.</p><div class="response-surface">Slope: _____</div>`,String(m),'Use (y2-y1)/(x2-x1).');}
      case 'U1-MG02-IC02-H': {const m=pick([-4,-3,-2,2,3,4]),x1=ri(-3,3),x2=x1+pick([2,3,4]),y1=ri(-8,8),y2=y1+m*(x2-x1);return inst(`<p>From x=${x1} to x=${x2}, y changes from ${y1} to ${y2}. What is the slope or rate of change?</p><div class="response-surface">Slope: _____</div>`,String(m),'Divide the output change by the input change.');}
      case 'U1-MG02-IC02-I': {const m=pick([2,3,4]),b=ri(-2,4),rowsA=linearRows(m,b,[0,1,2]),rowsB=[[0,b],[1,b+m],[2,b+2*m+pick([1,2])]];const swap=Math.random()<.5;return inst(`<p>Which table has a constant rate of change? Explain.</p><p><b>Table A</b></p>${tableHtml(swap?rowsB:rowsA)}<p><b>Table B</b></p>${tableHtml(swap?rowsA:rowsB)}<div class="response-surface">Table + explanation:</div>`,swap?'Table B.':'Table A.',`The constant table changes by ${m} in y for each 1 in x.`);}
      case 'U1-MG02-IC02-J': {const m=pick([-4,-3,-2,2,3,4]),b=ri(-4,4),xs=[1,4,8],rows=linearRows(m,b,xs),claim=Math.random()<.5?m:m+pick([-1,1]);return inst(`<p>Claim: “The table has slope ${claim}.” Verify using both intervals.</p>${tableHtml(rows)}<div class="response-surface">Verification:</div>`,claim===m?'True.':`False; the slope is ${m}.`,'Compute the slope on both intervals.');}
      case 'U1-MG02-IC03-A': {const m=pick([-6,-5,-4,-3,-2,2,3,4,5,6]),b=ri(-9,9);return inst(`<p>Find the slope of ${math(linearEq(m,b))}.</p><div class="response-surface">Slope: ______</div>`,String(m),'The slope is the coefficient of x.');}
      case 'U1-MG02-IC03-B': {const r=pick([rat(-3,2),rat(2,3),rat(-4,3),rat(3,4)]),b=ri(-8,8);const eq=`y=${b}${r.n>=0?'+':''}${r.text}x`;return inst(`<p>Find the slope of ${math(eq)}. Explain how you know.</p><div class="response-surface">Slope + explanation:</div>`,r.text,'The slope is the coefficient of x even when the constant is written first.');}
      case 'U1-MG02-IC03-C': {const m=pick([-6,-5,-4,-3,-2,2,3,4,5,6]),b=ri(2,9),student=pick(NAMES),eq=`y=${b}${m>=0?'+':''}${signedTerm(m)}`.replace('+-','-');return inst(`<p>${student} says the slope of ${math(eq)} is ${b} because ${b} comes first. Explain the error and state the slope.</p><div class="response-surface">Explain:</div>`,`The slope is ${m}. The number ${b} is the y-intercept; slope is the coefficient of x.`,'Slope is the x coefficient.');}
      case 'U1-MG02-IC03-D': {const k=pick([2,3,4]),m=pick([-4,-3,-2,2,3,4]),b=ri(-6,6),rhsX=k*m,rhsB=k*b,eq=`${k}y=${rhsX}x${rhsB>=0?'+':''}${rhsB}`;return inst(`<p>Find the slope of ${math(eq)}. Show the rewrite that makes slope visible.</p><div class="response-surface">Rewrite + slope:</div>`,`${linearEq(m,b)}; slope ${m}.`,'Divide every term by the coefficient of y.');}
      case 'U1-MG02-IC03-E': {const m=pick([-5,-4,-3,-2,2,3,4,5]),b=ri(2,9);const correct=linearEq(m,b),choices=[math(correct),math(linearEq(b,m)),math(linearEq(-m,b)),math(linearEq(m,-b))];return mc(`Which equation has slope ${math(String(m))}?`,choices,0,'Choose the equation whose x coefficient is the stated slope.');}
      case 'U1-MG02-IC03-F': {const r=pick([rat(-5,2),rat(-4,3),rat(-3,4),rat(2,5),rat(3,4),rat(4,3)]);return inst(`<p>The slope is ${fracMath(r)}. What are the rise and run?</p><div class="response-surface">Rise: _____ &nbsp; Run: _____</div>`,`Rise = ${r.n}; run = ${r.d}.`,'Use the signed numerator as rise and positive denominator as run.');}
      case 'U1-MG02-IC03-G': {const r=pick([rat(-5,2),rat(-4,3),rat(-3,4),rat(2,5),rat(3,4),rat(4,3)]);return mc(`The slope is ${fracMath(r)}. Which rise and run match this slope?`,[`rise ${r.n}, run ${r.d}`,`rise ${r.d}, run ${r.n}`,`rise ${-r.n}, run ${r.d}`,`rise ${r.n}, run ${-r.d}`],0,'Numerator gives rise; denominator gives run.');}
      case 'U1-MG02-IC03-H': {const r=pick([rat(-5,2),rat(-4,3),rat(-3,4),rat(2,5),rat(3,4),rat(4,3)]),b=ri(-7,7);return inst(`<p>For ${math(`y=${r.text}x${b>=0?'+':''}${b}`)}, what are the rise and run?</p><div class="response-surface">Rise: _____ &nbsp; Run: _____</div>`,`Rise = ${r.n}; run = ${r.d}.`,'Read the x coefficient as a fraction.');}
      case 'U1-MG02-IC03-I': {const r=pick([rat(-5,2),rat(-4,3),rat(-3,4),rat(2,5),rat(3,4),rat(4,3)]);return inst(`<p>Slope = ${fracMath(r)}.</p><p>Rise = <b>_____</b> and run = <b>_____</b>.</p>`,`${r.n}; ${r.d}`,'Use numerator for rise and denominator for run.');}
      case 'U1-MG02-IC03-J': {const m=pick([-5,-4,-3,2,3,4,5]),b1=ri(-6,6),b2=ri(-6,6),b3=ri(-6,6);return inst(`<p>For each equation, fill in a rise and run that match its slope.</p>${tableHtml([[math(linearEq(1,b1)),'_____ / _____'],[math(linearEq(-1,b2)),'_____ / _____'],[math(linearEq(m,b3)),'_____ / _____']],'Equation','Rise / Run')}`,`(1,1); (-1,1); (${m},1)`,'For integer slope m, use rise=m and run=1.');}
      case 'U1-MG02-IC04-A': {const rate=pick([4,6,8,10,12]),x1=ri(1,4),x2=x1+pick([2,3,4]),y1=ri(20,60),y2=y1+rate*(x2-x1);return inst(`<p>A tank contains ${y1} L of water after ${x1} minutes and ${y2} L after ${x2} minutes. Find the rate of change and interpret it.</p><div class="response-surface">Rate + meaning:</div>`,`${rate} L/min; the amount of water increases by ${rate} liters each minute.`,'Compute change in liters divided by change in minutes.');}
      case 'U1-MG02-IC04-B': {const rate=pick([6,8,10,12,15]),b=pick([10,20,25,30]);return inst(`<p>The graph shows total cost versus hours. Find the rate of change and explain what it means.</p>${lineGraphSvg({m:rate,b,xMax:6,yStep:10,xLabel:'Hours',yLabel:'Cost ($)'})}<div class="response-surface">Rate + meaning:</div>`,`$${rate} per hour; cost increases by $${rate} for each additional hour.`,'Slope of the context graph is the rate.');}
      case 'U1-MG02-IC04-C': {const rate=pick([12,15,18,20]),fee=pick([20,25,30,35]),student=pick(NAMES);return inst(`<p>A gym charges according to ${math(`C=${rate}h+${fee}`)}, where h is hours and C is cost in dollars. ${student} says, “The rate is $${fee} per hour.” Explain the error and state the actual rate.</p><div class="response-surface">Diagnosis:</div>`,`The rate is $${rate} per hour; $${fee} is the starting fee.`,'The x coefficient is the rate; the constant is the initial value.');}
      case 'U1-MG02-IC04-D': {const rate=pick([3,4,5,6]),x1=ri(1,4),x2=x1+3,fee=pick([4,6,8]),y1=rate*x1+fee,y2=rate*x2+fee;return inst(`<p>A delivery service records total cost.</p>${tableHtml([[x1,`$${y1}`],[x2,`$${y2}`]],'Miles','Cost')}<p>Find and interpret the rate of change.</p><div class="response-surface">Rate + meaning:</div>`,`$${rate} per mile; cost increases $${rate} for each additional mile.`,'Compute Δcost/Δmiles.');}
      case 'U1-MG02-IC04-E': {const aRate=pick([4,5,6,7]),bRate=aRate+pick([-2,-1,1,2]),aIn=pick([2,3,4]),bIn=pick([2,4,5]),aAmt=aRate*aIn,bAmt=bRate*bIn,lower=aRate<bRate?'A':'B';return inst(`<p>Plan A charges $${aAmt} for ${aIn} hours. Plan B charges $${bAmt} for ${bIn} hours. Which plan has the lower hourly rate?</p><div class="response-surface">Rates + choice:</div>`,`Plan A: $${aRate}/h; Plan B: $${bRate}/h; Plan ${lower} is lower.`,'Compute each unit rate before comparing.');}
      case 'U1-MG02-IC04-F': {const time=pick([2,3,4,5]),rate=pick([4,6,8,10]),amount=time*rate;return mc(`A printer makes ${amount} pages in ${time} minutes at a constant rate. Which rate is correct?`,[`${rate} pages per minute`,`${time} pages per minute`,`${amount-time} pages per minute`,`${amount*time} pages per minute`],0,'Unit rate = pages divided by minutes.');}
      case 'U1-MG02-IC04-G': {const words=shuffle(['per','each','every','total']);return inst(`<p><b>Word bank:</b> ${words.join(', ')}</p><p>Which three words often signal a rate of change?</p><div class="response-surface">Words: __________</div>`,'per, each, every','These words indicate a quantity for each one unit of another quantity.');}
      case 'U1-MG02-IC04-H': {const t=ri(1,5),v=ri(20,80);return inst(`<p>A tank has ${v} L at ${t} minutes. Is that enough to find its rate? What else is needed?</p><div class="response-surface">Answer:</div>`,'No; another time-volume measurement or equivalent change information is needed.','A rate needs a change in output and a change in input.');}
      case 'U1-MG02-IC04-I': {const rate=pick([4,6,8,10,12]),input=ri(2,6),newInput=input+pick([2,3,4]),value=ri(30,90),newValue=value+rate*(newInput-input);return inst(`<p>Rate = ${rate} L/min. The tank has ${value} L at ${input} min. How much at ${newInput} min?</p><div class="response-surface">Value: _____ L</div>`,`${newValue} L`,'Add rate × elapsed time to the known value.');}
      case 'U1-MG02-IC04-J': {const rate=pick([4,6,8,10,12]),x1=ri(1,5),x2=x1+pick([2,3,4]),y1=ri(20,80),y2=y1+rate*(x2-x1);return inst(`<p>A tank contains ${y1} L at ${x1} minutes and ${y2} L at ${x2} minutes. Find the rate of change.</p><div class="response-surface">Rate: _____ L/min</div>`,`${rate} L/min`,'Use (y2-y1)/(x2-x1).');}
      default:return null;
    }
  }
  window.AssessmentGeneration={supports:fid=>/^U1-MG0[12]-IC0[1-4]-[A-J]$/.test(String(fid)),generate:(family)=>generate(family.family_id)};
})();
